### ISSUE TITLE
SIGABRT when i use DFUServiceInitiator().with(firmware: firmware)

### ISSUE THREAD

**Issue by aflorentin** [NordicSemiconductor/IOS-Pods-DFU-Library#461]
**Information**
This GitHub Issue page is for reporting issues or asking questions regarding the iOS DFU library. For general DFU questions, SDK questions, etc, please check our [DevZone](https://devzone.nordicsemi.com/).
Make sure you are using the latest version of the library: [![Version](http://img.shields.io/cocoapods/v/iOSDFULibrary.svg)](http://cocoapods.org/pods/iOSDFULibrary)
Also, before creating a new issue, make sure similar issue isn't already opened in [open](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues) or [closed](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library/issues?q=is%3Aissue+is%3Aclosed) issues.

**DFU Bootloader version (please complete the following information):**
 - Library version: 4.11.1

**Device information (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: IOS 14.6, IOS 15.0

**Describe the bug**
Hi, I was using the version '4.6.1' for a long time now and i have no problem to update my DFU device.
I had to upgrade to the latest version (4.11.1) because of Xcode and since i got a SIGABRT when i use DFUServiceInitiator().with(firmware: selectedFirmware).

![First](https://user-images.githubusercontent.com/59833766/136921910-42c4800f-94cf-44a6-b46a-cc74a662ef6f.png)

![Second](https://user-images.githubusercontent.com/59833766/136921939-ae782f4d-226c-435a-ab9d-9fed74c4929d.png)

I have an application version with library version 4.6.1 that I use to test my firmware and the update is going well.

If you have an idea.
Thank you very much

**Comment by philips77** [comment]
Hello,
This looks like an issue with xcode. Try clearing caches, perhaps rebuilding frameworks if you're using Carthage, etc.
Does it happen every time?

**Comment by philips77** [comment]
This is the method that you have issue with:
https://github.com/NordicSemiconductor/IOS-DFU-Library/blob/f73213f2de57c8c53700725ee2cff6cd35ef66fe/iOSDFULibrary/Classes/Implementation/DFUServiceInitiator.swift#L396-L400

**Comment by aflorentin** [comment]
Hi, thank you for your answer yes this happen every time when i try to  update and I use Cocoapod.
I will try to clear my caches

**Comment by aflorentin** [comment]
I clear my caches but nothing change
