### ISSUE TITLE
Carthage unable to build the framework

### ISSUE THREAD

**Issue by joonaservald** [NordicSemiconductor/IOS-Pods-DFU-Library#518]
**DFU Bootloader version (please complete the following information):**
 - Library version: 4.13.0

**Describe the bug**
Following the README steps for carthage produces the following issue: 
`Dependency "IOS-DFU-Library" has no shared framework schemes for any of the platforms: iOS`

**Logs**
```
*** Fetching IOS-DFU-Library
*** Fetching ZIPFoundation
*** Checking out IOS-DFU-Library at "1.0.9b(19)"
*** xcodebuild output can be found in /var/folders/sz/qbg6lq6j5csf6m_wt5cntr_c0000gn/T/carthage-xcodebuild.oOO5yr.log
*** Skipped building IOS-DFU-Library due to the error:
Dependency "IOS-DFU-Library" has no shared framework schemes for any of the platforms: iOS
```
If you believe this to be an error, please file an issue with the maintainers at https://github.com/NordicSemiconductor/IOS-DFU-Library/issues/new

**Comment by philips77** [comment]
I tried creating a new project and setting up the DFU dependency using Carthage for version 4.13 using Cartfile:
```
github "NordicSemiconductor/IOS-DFU-Library" ~> 4.13.0
```

Log output:
```bash
❯ carthage update --use-xcframeworks --platform iOS
*** Fetching IOS-DFU-Library
*** Fetching ZIPFoundation
*** Checking out IOS-DFU-Library at "4.13.0"
*** Checking out ZIPFoundation at "0.9.11"
*** xcodebuild output can be found in /var/folders/72/nw5d7n_x23j_r5h0f8q4q8800000gn/T/carthage-xcodebuild.JKb5fy.log
*** Building scheme "ZIPFoundation" in ZIPFoundation.xcodeproj
*** Building scheme "iOSDFULibrary-iOS" in iOSDFULibrary.xcworkspace
```

Using the "main" branch indeed doesn't work yet and I get the issue you described.
