### ISSUE TITLE
Cocoapods after 4.13.0 are not working

### ISSUE THREAD

**Issue by aetrocks** [NordicSemiconductor/IOS-Pods-DFU-Library#543]
Hello everyone,

We are currently using Kotlin Multiplatform to combine the iOS and android nordic dfu libraries as one multiplatform Firmware library for our devices.

I made a test to import the iOSDFULibrary as "iOSDFULibrary" and afterwards as "NordicDFU".
Both with Versions 4.13.0 and as 4.14.0, 4.15.0 and 4.15.3.

The Pods are not found in neither way if the Version is after 4.13.0.

Would it be possible that you could consider checking it yourself with those versions in a plain Xcode project?
Try to use a newer Version of iOSDFULibrary other than 4.13.0.

This is a major Problem for us, because at the moment, we cannot update our apps for customers, because of this.

Thanks in advance and best regards
Simon

**Comment by philips77** [comment]
Hello,
Did you try `pod cache clean` and `pod search iOSDFULibrary`?

**Comment by philips77** [comment]
This https://cocoapods.org/pods/iOSDFULibrary shows latest version 4.15.3.

**Comment by philips77** [comment]
```console
❯ pod --version
1.16.2
❯ pod install
Analyzing dependencies
Downloading dependencies
Installing ZIPFoundation (0.9.19)
Installing iOSDFULibrary (4.15.3)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `TestApp.xcworkspace` for this project from now on.
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
```

**Comment by aetrocks** [comment]
Okay I saw the Problem pretty fast aber your comment here, sorry. :| 

I should sometimes update my cocoapods ....

Now I still get DFULib not found but it's related to missing klibs and so a Problem regarding Kotlin and iOS.
Kotlin Multiplatform and native iOS libraries are so fun to work with...

Thanks for your support and fast replies.
